### ISSUE TITLE
Polygon - bruksområder

### ISSUE THREAD

**Issue by runningbones** [Artsdatabanken/okologiskegrunnkart#173]
**Aktuelle bruksområder for polygoner (#172)**

## Del 1. Tegne og laste opp et polygon
- kun for å se det på kartet #25. 
- Utsetter #26 inntil videre.
- Samsvar mellom actionknappene og tegnerern

EDIT etter diskusjon med @bjornreppen:
- [x] FØRSTE og SISTE punkt har en sirkel eller noe markert.
- [x] Sirklene kan være aktive eller passive
- [x] En aktiv sirkel viser at du kan redigere fra dette punktet
- [x] En passiv sirkel er det samme som at linja er "ferdig"
- [x] Når du har en aktiv sirkel, og klikker på den andre sirkelen, lukker det seg til et ferdig polygon
- [x] Om du har en aktiv sirkel og klikker på den, blir den inaktiv, altså en uredigerbar linje som er det samme som en ferdig linje
- [x] Om du har to passive sirkler og trykker på en av dem, blir denne valgt som aktiv.

## Del 2. Knapper under polygontegneren med valgalternativer for hva du vil bruke det til:
- [x] lengde, areal:
   - Kjøre en arealsprørring mot utvalgte kartlag for å få en "arealrapport". 
   - eks. https://kilden.nibio.no/ (vektøy/arealrapport) 
   - dialog med kartlag som kan inngå i rapport
   - bør også tilbys for utvalgte objekttyper: eks eiendom, kommune m.fl.
- [ ] høydeprofil langs polylinja -> Ø finner api referanse? 
- [x] identify/klikk i kart, se neste punkt

## Del 3. Bruke polygonet for å identifisere objekter i kartet (ala klikkikart) 
- [x] får opp liste over tilgjengelige lag å velge fra for identify
- [x] @bjornreppen lager mulighet for å hente ut polygondata for identify

## Del 4. Kobling mot artskart
- [ ] dratt med fra artskart innafor polygon - drøft. egen issue.
- [ ] Benytte polygonet for å finne alle arter fra artskart ved å gjenbruke polygonets geometri 
    - sende til/embed https://artskart.artsdatabanken.no/app/#list/263259,7011304/17/background/greyMap/filter/%7B%22IncludeSubTaxonIds%22%3Atrue%2C%22Found%22%3A%5B2%5D%2C%22Geometry%22%3A%22POLYGON((263131.5205078125%207011391.655517577%2C263094.82763671875%207011124.888427733%2C263348.70263671875%207011126.210693358%2C263296.142578125%207011349.012451171%2C263131.5205078125%207011391.655517577))%22%2C%22Style%22%3A1%7D
   - bør også tilbys for utvalgte objekttyper: eks eiendom, kommune m.fl.

**Comment by helemork** [comment]
Min visjon:
* Tegning bør ikke automatisk generer data. 
* Jeg hadde sett for meg at vi hadde et par knapper under polygontegneren:

1. hent ut koordinat (så kan de lagre/gjøre hva de vil med dem)
2. regn ut areal
3. hent ut data i punkt fra valgte kartlag

**Comment by runningbones** [comment]
Høydeprofil: https://www.kartverket.no/data/Hoydeprofil/

**Comment by runningbones** [comment]
Viktig poeng å ta stilling til: polygonverktøy vil ved bruk av EPSG:3857 gi en del merkelige konsekvenser sammenholdt med en flatriktig projeksjon (eks espg: 25833). Kan beregning gjøres i 25833, mens klient er i EPSG:3857? Hvilken støtte har leaftlet for 25833?

**Comment by bjornreppen** [comment]
En del trøbbel med Høydeprofil-tjenesten https://www.kartverket.no/data/Hoydeprofil/  .. i tillegg til at den krever at man sette opp en egen web server og så laste opp en GPX-fil til denne for at tjenesten skal kunne laste koordinatene derfra... istedet for at de kan ligge i requesten.

![image](https://user-images.githubusercontent.com/281359/89124676-1e537880-d4d9-11ea-99c5-4165e628b15f.png)
