### ISSUE TITLE
Artskartdata fra API

### ISSUE THREAD

**Issue by runningbones** [Artsdatabanken/okologiskegrunnkart#210]
Fremmede arter (ID-36) og Rødlsita arter (ID-31) hentes nå som wms. Ønsker å forsøke å "bytte ut" disse wms-tjenestene med:

 ̵h̵t̵t̵p̵:̵/̵/̵w̵e̵b̵t̵j̵e̵n̵e̵s̵t̵e̵r̵.̵a̵r̵t̵s̵d̵a̵t̵a̵b̵a̵n̵k̵e̵n̵.̵n̵o̵/̵A̵r̵t̵s̵k̵a̵r̵t̵/̵h̵e̵l̵p̵ https://artskart.artsdatabanken.no/publicapi/help

**Comment by bjornreppen** [comment]
Noe hemmet av https://github.com/Artsdatabanken/Artskart/issues/23

**Comment by runningbones** [comment]
@bjornreppen : jeg kan ha bommet, dette API-et ser nyere ut: https://artskart.artsdatabanken.no/publicapi/help og åpner for andre projeksjoner

**Comment by runningbones** [comment]
Er dette det samme API-et eller et annet? Hva er det nye og hva er det gamle?https://artskart.artsdatabanken.no/publicapi/help

**Comment by bjornreppen** [comment]
Mulig nyere(?) @steinho, men denne ser heller ikke ut til å høre på "crs"-parametret.. får akkurat samme resultat etter å ha endret crs med uendret bbox.

**Comment by runningbones** [comment]
Dersom mulig:
Vise geometri i kartet fra API (og ikke wms) (punkter og flater):
- [ ] Rødlsista arter (erstatte id-31)
- [ ] Fremmede arter (erstatte id-36)

Klikk i kart
- [ ] Retunere treff fra API (Liste?)
- [ ] "Faktark": lenke til Artkart med filter i URL?

Polygon-tool
- [ ] Retunere treff fra API i polygonspørring

**Comment by runningbones** [comment]
I følge @steinho må koordinatene for polygonspørring i Artskarts API alltid være i espg: 25833 https://spatialreference.org/ref/epsg/etrs89-utm-zone-33n/

**Comment by bjornreppen** [comment]
Blokkert av https://github.com/Artsdatabanken/Artskart/issues/23
