### ISSUE TITLE
Søk i alle kartlag

### ISSUE THREAD

**Issue by runningbones** [Artsdatabanken/okologiskegrunnkart#215]
Klikk i kart/infobox nå: getfeatureinfo fra alle "aktive" kartlag, men mulighet for å søke i alle kartlag ved hjelp av egen knapp
![image](https://user-images.githubusercontent.com/31729342/83865100-fa1c2b00-a725-11ea-837c-81eb029bda0a.png)

Denne knappen kan erstattes med en switch (on/off) f.eks: 
![image](https://user-images.githubusercontent.com/31729342/83865756-f0df8e00-a726-11ea-9b11-bb96f7a76df4.png)

**Comment by helemork** [comment]
P.S. noen av oss er ikke helt fan av de switchene som er i material og har derfor.. laget en egen. Eksempel ligger her: 
![image](https://user-images.githubusercontent.com/17450081/83943890-c6153880-a7ff-11ea-9455-e0d5ceca63c4.png)
