### ISSUE TITLE
Tema - ikon

### ISSUE THREAD

**Issue by runningbones** [Artsdatabanken/okologiskegrunnkart#236]
Finn ikoner (.svg) for bruk i karetlagsliste. Et  ikon per tema. Legg inn tabell med temanavn og ikonnavn (samt kilde?)

**Comment by runningbones** [comment]
@kepatinin fint om du kan legg inn lenkt til preferert i kongalleri

**Comment by runningbones** [comment]
Tema | Icon | gallery
-- | -- | --
Marint | waves | https://materialdesignicons.com/
Arter | bee-flower | https://materialdesignicons.com/
Geologi | pickaxe | https://materialdesignicons.com/
Ferskvann | water | https://materialdesignicons.com/
Miljøvariabel | grid | https://materialdesignicons.com/
Klima | weather-partly-snowy-rainy | https://materialdesignicons.com/
Landskap | image-filter-hdr | https://materialdesignicons.com/
Naturtyper | natursystem_ikon.png | https://nin.artsdatabanken.no/logoer/
Arealressurs |   |  
Skog | pine-tree | https://materialdesignicons.com/

**Comment by runningbones** [comment]
Arealressurs: leter etter et ikon ala 
![image](https://user-images.githubusercontent.com/31729342/85107361-251a7a80-b20e-11ea-82c9-5a8c249ee6e6.png)

**Comment by kepatinin** [comment]
@runningbones bra forslag! :) ser at du har brukt en annen kilde for `Naturtyper`. Har vi svg data for den ikonen?
E.g.:
`<svg style="width:24px;height:24px" viewBox="0 0 24 24">
    <path fill="currentColor" d="M21,7L9,19L3.5,13.5L4.91,12.09L9,16.17L19.59,5.59L21,7Z" />
</svg>`

**Comment by runningbones** [comment]
@helemork har laget ikonet, men jeg finner det kun i png...

**Comment by helemork** [comment]
jeg har ikke laget den i svg nei, men har vel fila i photoshop så det kan kanskje konverteres? idk.

- @runningbones, ditt forslag og arealressurs ser ut som en quidditch bane og quidditch ikoner, så mulig den er litt off. antar de skal være trær? hva prøver du å uttrykke? Hva med "nature-people" siden det er ting folk må bruke der ting er?
- er litt uenig i å bruke grid for miljøvariabel, da det ofte brukes om å fysisk legge på en grid på kartet, hva med "graphql" eller en annen form for grafikon som "chart-bell-curve-cumulative" ?
- synes bie og blomst ikon er litt vanskelig å se hva er, hva med "graph"? ser ut som et artstre :)

**Comment by runningbones** [comment]
@kepatinin Ikontabell oppdatert!

**Comment by runningbones** [comment]
Forslag til ikon for administrative støttekart: https://materialdesignicons.com/icon/shield (@kepatinin tabell oppdatert)
