### ISSUE TITLE
Admin gir 403 ved pålogging

### ISSUE THREAD

**Issue by runningbones** [Artsdatabanken/okologiskegrunnkart#478]
**Describe the bug**
https://okologiskegrunnkartadmin.artsdatabanken.no/admin/login/?next=/admin/ gir 403 ved pålogging

**To Reproduce**
1. Go to '[...](https://okologiskegrunnkartadmin.artsdatabanken.no/admin/login/?next=/admin/)'
2. Put in user and password
3. See error

**Expected behavior**
log in

**Screenshots**
![image](https://user-images.githubusercontent.com/31729342/167087233-8286cefa-daf3-4a63-b076-ec6fee4c6cde.png)

**Comment by runningbones** [comment]
Rimelig kritisk at vi ikke har mulighet til å oppdatere kartlagslita: har flere kartlag som må endres, samt noen nye som skal legges til.

**Comment by helemork** [comment]
@steinho Jeg tror kanskje dette er en type kalibrering vi trenger litt hjelp til av deg.

**Comment by runningbones** [comment]
klarte nå å deploye, men fortsatt 403. Kan det være relatert til django versjon?

**Comment by runningbones** [comment]
@Myrdrahl: Helene har nå bygd lokalt, og der funker alt. Problemene er dermed kun å finne på prod-versjon i Docker. Noen ide?

**Comment by Myrdrahl** [comment]
Fixed.
