### ISSUE TITLE
Identity server

### ISSUE THREAD

**Issue by runningbones** [Artsdatabanken/okologiskegrunnkart#98]
Bruk https://github.com/Artsdatabanken/IdentityServer4 til brukeradmin og autentisering for pålogging i djangobasen

**Comment by helemork** [comment]
@steinho 
Tidligere da vi var i første planlegging av forvaltningsportalen som prosjekt, ble det nevnt at alt burde lages med tanke på at det skal kunne være mulig å eventuelt overføre prosjektet ut fra Artsdatabanken ved en senere anledning. F.eks hvis noen av vår samarbeidspartnere ønsker å overta hosting og forvaltning av prosjektet på sikt.

I denne forbindelse lurte jeg på om det er ønskelig at vi skal bruke tid på å få koblet inn identityserver mot vårt brukeradminpanel? 

Denne koblingen vil jo setter opp et tett bånd mot våre egne login-systemer, som potensielt kan være noe knotete å bli kvitt senere. Jeg vil også anta det vil ta litt tid å finne ut hvordan å koble det sammen på en god måte, uten at jeg har hverken sett på eller vært borti identityserver. 

I første omgang skal jo brukerpanelet utelukkende benyttes av brukere vi har kontroll over og administrerer tilganger til, da vi ønsker å begrense dem med kun leserettigheter i databasen, og kun mot sine egne datasett - sånn at en admin gjør de faktiske endringene. Slik kan vi unngå potensiell krøll med datasettene. Med andre ord er det ikke så mange det er snakk om, og det spørs om de har en bruker på identityserver i utgangspunktet heller? Det er jo ikke direkte overlapp med våre andre system.

Så mitt spørsmål er vel egentlig: Er denne koblingen noe vi ønsker eller ikke? Isåfall trenger vi nok noe hjelp til å finne ut hva denne identityserveren er for noe :)

**Comment by steinho** [comment]
https://id.artsdatabanken.no/ leverer autentisering og tilgang til brukere og api'er som krever tilgang - med åpne standarder som OpenId connect og oauth 2. 

Med andre ord - det er ikke Identityserver som teknologi men kopler til mot. Ved å bruke denne type autentisering skal man være forberedt i forhold til å bytte den ut med andre tredjeparts autentiseringer - uten vesentlig behov for kodeendringer utover konfigurasjon.

Om man f.eks. senere finner ut at autentisering via id-porten er nødvendig - er man forberedt på det - https://difi.github.io/felleslosninger/oidc_index.html. Det siste er noe Rødliste-gjengen spekulerte på da de ønsket å sikre seg at folk ikke låner bort brukerkontoene sine i rødlistearbeidet.
Miljødirektoratet har allerede egen Identityserver installasjon med tanke på tilsvarende formål.

Tenker vi kan ta et møte og se på hvilket behov man har. Det er fordeler ved å ha autentisering samlet en plass.

**Comment by helemork** [comment]
Et møte høres lurt ut. Når eventuelt tar vi det? Innser møter er litt knotete å få til sånn for øyeblikket over nett, men hvis jeg skal kunne bidra med innspill bør det nok ikke utsettes for lenge heller.  Sommeren kommer fort ;) Vil anta det blir @bjornreppen som implementerer det om vi velger å blande det inn. Og jeg antar både @runningbones og sikkert også @Myrdrahl har meninger om saken :)
